branches:
  only:
    - master

cache:
  directories:
    - $HOME/.portage-pkgdir

matrix:
  include:
    - os: linux
      services: docker
      language: generic
      sudo: required
      script:
        - 'if [ "${TRAVIS_EVENT_TYPE}" != "cron" ]; then
          docker run --rm -ti -v "${HOME}"/.portage-pkgdir:/usr/portage/packages -v "${PWD}":/home/myhome/SAMRI -w /home/myhome/SAMRI gentoo/stage3-amd64:latest /home/myhome/SAMRI/installdeps.sh; fi'
        - echo isntcron
        - pwd
        - ls
        - ls "${HOME}"
        - ls "${HOME}"/.portage-pkgdir
    - os: linux
      env: BUILD_TYPE=newversioncheck # marker environment variable to make the build matrix more readable in the UI
      services: docker
      language: generic
      sudo: required
      script:
        - 'if [ "${TRAVIS_EVENT_TYPE}" == "cron" ]; then
          docker run --rm -ti -v "${HOME}"/.portage-pkgdir:/usr/portage/packages -v "${PWD}":/usr/local/portage -w /usr/local/portage gentoo/stage3-amd64:latest emerge --sync; fi'
        - echo iscron
        - ls
        - pwd
