sudo: required
language: python
services:
  - docker
python:
  - "2.7"
  - "3.5"
before_install:
  - docker pull gentoo/portage
  - docker run -d -p 127.0.0.1:80:4567 gentoo/portage /bin/sh -c "pwd; ls; cd gentoo/portage"
  - docker ps -a
  - docker run carlad/sinatra /bin/sh -c "pwd; ls; cd gentoo/portage"
before_script:
  - pwd
  - ls
script:
  - pwd
  - ls
  - emerge -pv numpy
  - ./../spinner.sh "python ../portage-portage-${PORTAGE_VER}/repoman/bin/repoman full -d"
