sudo: required
language: python
services:
  - docker
python:
  - "2.7"
  - "3.5"
before_install:
  - docker pull gentoo/stage3-amd64
  - docker run -d -p 127.0.0.1:80:4567 gentoo/stage3-amd64
  - docker ps -a
  - docker run gentoo/stage3-amd64 /bin/sh -c "pwd; ls; emerge -pv numpy"
before_script:
  - pwd
  - ls
script:
  - pwd
  - ls
  - emerge -pv numpy
  - ./../spinner.sh "python ../portage-portage-${PORTAGE_VER}/repoman/bin/repoman full -d"
