language: python
python:
	- "2.7"
	- "3.5"
before_install:
	- cd ../../..
	- wget https://gitweb.gentoo.org/repo/proj/prefix.git/plain/scripts/bootstrap-prefix.sh
	- pwd
	- ls
	- chmod +x bootstrap-prefix.sh
	- yes "" | ./bootstrap-prefix.sh
before_script:
	- pwd
	- ls
script:
	- pwd
	- ls
	- emerge -pv numpy
	- ./../spinner.sh "python ../portage-portage-${PORTAGE_VER}/repoman/bin/repoman full -d"
